name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure GIT
        run: |
          git config --global user.email "upsolver-cli-bot@github.com"
          git config --global user.name "CLI Release Github Bot"

      - name: Determine Version
        id: release-version
        run: |
          echo "::set-output name=full::${{ github.ref_name }}"
          SIMPLE=$(echo ${{ github.ref_name }} | sed -e s/^v//)
          echo "::set-output name=simple::$SIMPLE"

      - name: Update Version
        run: |
          pwd
          ls cli
          echo "SIMPLE_VERSION == ${{ steps.release-version.outputs.simple }}"
          sed -i -e "s/.*__version__.*/__version__ = '${{ steps.release-version.outputs.simple }}'/g" cli/__init__.py
          sed -i -e "s/.*version =.*/version = \"${{ steps.release-version.outputs.simple }}\"/g" pyproject.toml

      - name: Extract Change Notes
        id: extract_changes
        run: |
          CHANGES=$(sed -n "/^# ${{ steps.release-version.outputs.full }}$/,/^# /p" CHANGELOG.md  | grep -E "^(-|\s+)")
          if [ -z $CHANGES ]; then
            echo "::set-output name=ok::false"
          else
            echo "::set-output name=ok::true"
            echo "::set-output name=changes::=$CHANGES"
          fi

      - name: Fail on Empty Changelog
        uses: actions/github-script@v3
        if: ${{ steps.extract_changes.outputs.ok != 'true' }}
        with:
          scripts: |
            core.setFailed('Must have a section for ${{ steps.release-version.outputs.full }} in CHANGELOG.md')

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.x

      - name: Install Poetry
        run: |
          pip install poetry==1.1.13
          poetry install

      - name: Build Release Archive
        id: build-archive
        run: |
          poetry build

      - name: Generate homebrew formula
        run: |
          poetry run python scripts/gen-brew-formula.py --cli-archive-url "https://github.com/Upsolver/cli/releases/download/${{ github.ref_name }}/upsolver-cli.tar.gz" --compute-hash-from-file dist/cli-${{ steps.release-version.outputs.simple }}.tar.gz

      - name: Commit updated homebrew formula & version files
        run: |
          git commit -am "Release ${{ steps.release-version.outputs.full }}"
          git push origin HEAD:master

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.extract_changes.outputs.changes }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/cli-${{ steps.build-archive.outputs.version }}.tar.gz
          asset_name: upsolver-cli.tar.gz
          asset_content_type: application/tar+gz

      - name: Checkout Samples repo
        uses: actions/checkout@v2
        with:
          repository: Upsolver/Samples
          ref: master
          token: ${{ secrets.SAMPLES_ACCEESS_TOKEN }}
          path: Samples

      - name: Update pip install snippet in Samples repo
        run: |
          mkdir -p ./Samples/samples/cli/
          cd Samples
          echo "pip install https://github.com/Upsolver/cli/releases/download/${{ github.ref_name }}/upsolver-cli.tar.gz" > ./samples/cli/pip_install.sh
          git add ./samples/cli/pip_install.sh
          if [[ `git status --porcelain` ]]; then
              git commit -m "updated CLI pip installation command"
              git push origin HEAD:master
          fi
