name: Genereate homebrew formula
on:
  release:
    types: [published]
jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10.x]
        poetry-version: [1.1.13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install poetry==${{ matrix.poetry-version }}
      - run: poetry install
      - run: poetry run genformula.py --compute-hash-from-build
      - run: cat ./Formula/upsolver-cli.rb
      - run: |
          git config --local user.email "release-bot@github.com"
          git config --local user.name "GitHub Release Bot"
          git add ./Formula/upsolver-cli.rb
          git commit -m "Update homebrew formula"
          git push -u origin $(eval git branch --show-current)
