name: test-actions
on: [push]
jobs:
  test-job-name:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10.x]
        poetry-version: [1.1.13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pwd && ls -alh
      - run: |
          pip install poetry==${{ matrix.poetry-version }}
      - run: poetry install
      - run: poetry shell
      - run: poetry run python -m pytest tests
