name: Tests
on:
  static-code-checks-workflow:
    workflows: [Static Code Checks]
    types:
      - completed
jobs:
  run-tests:
    if: ${{ github.event.static-code-checks-workflow.conclusion == 'success' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10.x]
        poetry-version: [1.1.13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install poetry==${{ matrix.poetry-version }}
      - run: poetry install
      - run: poetry run python -m pytest tests
